- name: Create download directory
  file:
    path: '{{download_dir}}'
    state: directory

- name: Download AWS CLI
  get_url:
    url: '{{aws_cli_url}}'
    dest: '{{aws_cli_tmp}}'
    timeout: 600

- name: Extract AWS CLI
  become: yes
  unarchive:
    src: '{{aws_cli_tmp}}'
    dest: '{{download_dir}}'
    remote_src: yes
    owner: '{{user}}'

- name: Install AWS CLI
  become: yes
  command: '{{download_dir}}/aws/install --install-dir {{aws_cli_install_dir}} --bin-dir {{aws_cli_bin_dir}} --update'

