---

- name: Install packages
  become: yes
  apt:
    pkg:
      - openjdk-8-jdk
    update_cache: yes
    cache_valid_time: 86400
    state: latest

- name: Create XMind target directory
  become: yes
  file:
    path: '{{xmind_dir}}'
    state: directory
    owner: '{{user}}'

- name: Create XMind workspace directory
  become: yes
  file:
    path: '{{xmind_workspace_dir}}'
    state: directory
    owner: '{{user}}'

- name: Download and XMind
  become: yes
  unarchive:
    src: '{{xmind_url}}'
    dest: '{{xmind_dir}}'
    remote_src: yes
    owner: '{{user}}'
    creates: '{{xmind_dir}}/setup.sh'

- name: Adapt XMind configuration
  become: yes
  replace:
    path: '{{xmind_dir}}/XMind_amd64/XMind.ini'
    regexp: '{{item.regexp}}'
    replace: '{{item.replace}}'
  with_items:
    - {regexp: '^-configuration\n\./configuration\n', replace: '-configuration\n{{xmind_dir}}/XMind_amd64/configuration\n'}
    - {regexp: '^-data\n\.\./workspace\n', replace: '-data\n{{xmind_workspace_dir}}\n'}

- name: Create fonts directory
  file:
    path: '{{home}}/.fonts/'
    state: directory

- name: Copy fonts
  copy:
    src: '{{xmind_dir}}/fonts/'
    dest: '{{home}}/.fonts/'
    remote_src: yes
  notify: Refresh font cache

- name: Copy icon
  synchronize:
    src: 'xmind.png'
    dest: '{{xmind_dir}}'

- name: Install XMind desktop file
  become: yes
  template:
    src: xmind.desktop.j2
    dest: '/usr/share/applications/xmind.desktop'
    owner: root
    group: root
    mode: 'u=rw,go=r'
