Vagrant.require_version ">= 2.2.1"

Vagrant.configure(2) do |config|

  config.vm.box = "frostcode/devbox"
  config.vm.hostname = "devbox"
  config.ssh.password = "vagrant"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "devbox"
    vb.memory = "8096"
    vb.cpus ="4"
    vb.gui = true
  end

end
