- name: Create Terminal directory
  file:
    path: '{{home}}/.config/xfce4/terminal/'
    state: directory

- name: Configure Terminal
  copy:
    src: 'terminalrc'
    dest: '{{home}}/.config/xfce4/terminal/terminalrc'

- name: Create Terminator config directory
  file:
    path: '{{home}}/.config/terminator'
    state: directory

- name: Configure Terminator
  copy:
    src: 'terminator.config'
    dest: '{{home}}/.config/terminator/config'

- name: Configure bash
  lineinfile:
    dest: '{{home}}/.bashrc'
    regexp: '^alias ll='
    line: 'alias ll="ls -AlFhv --group-directories-first --time-style=long-iso --color=auto"'
    state: present

- name: Add bash prompt helper method
  blockinfile:
    path: '{{home}}/.bashrc'
    block: |
      parse_git_branch() {
        git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/\1/'
      }

- name: Configure bash prompt helper method
  lineinfile:
    dest: '{{home}}/.bashrc'
    line: 'PS1="\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]:\[\033[01;34m\]\[\033[01;31m\]$(parse_git_branch)\[\033[00m\]\$ "'
    state: present
