- name: Install packages
  become: yes
  apt:
    pkg:
      - exa
      - zsh
    update_cache: yes
    cache_valid_time: 86400
    state: latest
  notify: Clear apt cache

- name: Install snap packages
  become: yes
  command: 'snap install {{item}}'
  with_items:
    - starship

- name: Create fonts directory
  file:
    path: '{{home}}/.fonts/'
    state: directory

- name: Copy fonts
  synchronize:
    src: 'fonts/'
    dest: '{{home}}/.fonts/'
  notify: Refresh font cache

- name: Configure Starship
  copy:
    src: 'starship.toml'
    dest: '{{home}}/.config/starship.toml'

- name: Create Terminal directory
  file:
    path: '{{home}}/.config/xfce4/terminal/'
    state: directory

- name: Configure Terminal
  copy:
    src: 'terminalrc'
    dest: '{{home}}/.config/xfce4/terminal/terminalrc'

- name: Create Terminator config directory
  file:
    path: '{{home}}/.config/terminator'
    state: directory

- name: Configure Terminator
  copy:
    src: 'terminator.config'
    dest: '{{home}}/.config/terminator/config'

- name: Configure bash
  lineinfile:
    dest: '{{home}}/.bashrc'
    regexp: '^alias ll='
    line: 'alias ll="ls -AlFhv --group-directories-first --time-style=long-iso --color=auto"'
    state: present

- name: Add bash prompt helper method
  blockinfile:
    path: '{{home}}/.bashrc'
    block: |
      parse_git_branch() {
        git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/\1/'
      }

- name: Configure bash prompt helper method
  lineinfile:
    dest: '{{home}}/.bashrc'
    line: 'PS1=''\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]:\[\033[01;34m\]\[\033[01;31m\]$(parse_git_branch)\[\033[00m\]\$ '''
    state: present

- name: Configure Starship
  lineinfile:
    dest: '{{home}}/.bashrc'
    line: 'eval "$(starship init bash)"'
    state: present

- name: Set ZSH as default shell
  become: yes
  user:
    name: "{{user}}"
    shell: /bin/zsh

- name: Clone Oh My ZSH repository
  git:
    repo: 'git@github.com:ohmyzsh/ohmyzsh.git'
    dest: '{{home}}/.oh-my-zsh'
    accept_hostkey: yes
    update: no

- name: Clone Powerlevel10k theme repository
  git:
    repo: 'git@github.com:romkatv/powerlevel10k.git'
    dest: '{{home}}/.oh-my-zsh/custom/themes/powerlevel10k'
    accept_hostkey: yes
    update: no

- name: Clone ZSH plugin repositories
  git:
    repo: 'git@github.com:zsh-users/{{item}}.git'
    dest: '{{home}}/.oh-my-zsh/custom/plugins/{{item}}'
    accept_hostkey: yes
    update: no
  with_items:
    - zsh-autosuggestions
    - zsh-syntax-highlighting
    - zsh-history-substring-search

- name: Configure Powerlevel10k
  copy:
    src: 'p10k.zsh'
    dest: '{{home}}/.p10k.zsh'

- name: Configure ZSH
  copy:
    src: 'zshrc'
    dest: '{{home}}/.zshrc'
