---

home: '/home/{{user}}'
download_dir: '{{home}}/Downloads/Ansible'
firefox_url: 'https://download.mozilla.org/?product=firefox-latest-ssl&os=linux64&lang=de'
firefox_dir: '/opt'
firefox_desktop_file_url: 'https://raw.githubusercontent.com/mozilla/sumo-kb/main/install-firefox-linux/firefox.desktop'
