---

home: '/home/{{user}}'
openj9_version: '0.30.0'
openj9_url: 'https://github.com/ibmruntimes/semeru17-binaries/releases/download/jdk-17.0.2%2B8_openj9-0.30.0/ibm-semeru-open-jdk_x64_linux_17.0.2_8_openj9-0.30.0.tar.gz'
openj9_tmp: '/opt/openj9-{{openj9_version}}.tar.gz'
openj9_dir: '/opt/openj9-{{openj9_version}}'
openj9_link: '/opt/openj9'
graalvm_version: '22.0.0.2'
graalvm_url: 'https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-{{graalvm_version}}/graalvm-ce-java11-linux-amd64-{{graalvm_version}}.tar.gz'
graalvm_native_url: 'https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-{{graalvm_version}}/native-image-installable-svm-java11-linux-amd64-{{graalvm_version}}.jar'
graalvm_tmp: '/opt/graalvm-{{graalvm_version}}.tar.gz'
graalvm_dir: '/opt/graalvm-{{graalvm_version}}'
graalvm_native_path: '{{graalvm_dir}}/native-image-installable-svm-linux-amd64-{{graalvm_version}}.jar'
graalvm_link: '/opt/graalvm'
aws_cli_url: 'https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip'
aws_cli_tmp: '{{download_dir}}/awscliv2.zip'
aws_cli_install_dir: '/usr/local/aws'
aws_cli_bin_dir: '/usr/local/bin'
linuxbrew_bin_dir: '/home/linuxbrew/.linuxbrew/bin'
etcher_version: '1.7.8'
etcher_url: 'https://github.com/balena-io/etcher/releases/download/v{{etcher_version}}/balena-etcher-electron_{{etcher_version}}_amd64.deb'
etcher_tmp_deb: '{{download_dir}}/etcher-{{etcher_version}}.deb'
