name: Run packer build

on:
  push:
    branches: [ master ]

jobs:
  packer:
    runs-on: macos-latest
    name: packer

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Ansible
        run: brew install ansible

      - name: Build artifact
        run: packer build -on-error=abort -force -var 'git_email=change@me.org' -var-file=packer/xubuntu-20.04.json packer/xubuntu.json
        env:
          VAGRANT_CLOUD_TOKEN: ${{ secrets.VAGRANT_CLOUD_TOKEN }}
